services:
  backend:
    build:
      context: ./page_art
      dockerfile: Dockerfile
    container_name: django_b
    ports:
      - "8000:8000"
    env_file:
      - ./env_project/.env
    volumes:
      - ./page_art:/app
      - ./page_art/media:/app/media
      - ./page_art/actividades.db:/app/actividades.db
    networks:
      - backend
  frontend:
    build:
      context: ./Dashboard
      dockerfile: Dockerfile
    container_name: react_f
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    volumes:
      - ./Dashboard:/app
      - /app/node_modules
    command: ["yarn", "run", "dev"]
    networks:
      - frontend
      - backend
networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge